@startuml
'https://plantuml.com/class-diagram
skinparam classAttributeIconSize 0

class Webserver {
- {static} PORT :int
- {static} FORMATTER : DateTimeFormatter
+ Webserver()
}

class SocketThread {
- insocked : Socked
- makeRequest(tokens : String[]) : Request
- makeRequestReader(tokens : String[]) : RequestReader
- makeRequestArea(tokens : String[]) : RequestArea
- makeHeaderAnswer() : String
- makeJsonAnswer(request : Request) : String
+ run()
}

Webserver +-right- SocketThread

note right of SocketThread
inner class
of Webserver
end note

class DirectoryDoors {
- {static} allDoors : Door[]
+ {static} makeDoors()
+ {static} findDoorById(id : String) : Door
+ {static} getAllDoors() : Door[]
}

DirectoryDoors --> "*" Door : "allDoors"

class DirectoryUsers {
- {static} users : User[]
+ {static} makeUsers()
+ {static} findUserByCredential(credential : String) : User
}

DirectoryUsers --> "*" User : "users"

class Door {
- id : String
- closed : boolean
+ Door(id : String)
+ processRequest(request : RequestReader)
+ setState(doorState : DoorState)
+ toJson() : JSONObject
'+ toString() : String
'+ isClosed() :boolean
'+ setClosed(b : boolean)
'+ getStateName() : String
- doAction(action : String)
}


abstract class State {
    + void lock()
    + void unlock()
    + void unlockShortly()
    + void setDoor(Door door)
    + String getState()
    + void intClock()
}
class Locked {
    - Door door
    + Locked(Door door)
    + void unlock()
    + void lock()
    + void unlockShortly()
    + void setDoor(Door door)
    + String getState()
    + void intClock()
}
class Unlocked {
    - Door door
    + Unlocked(Door door)
    + void unlock()
    + void lock()
    + void unlockShortly()
    + void setDoor(Door door)
    + String getState()
    + void intClock()
}
' Abstract class declaration
abstract class Area {
    + String getName()
    + ArrayList<Door> getDoorsGivingAccess()
    + Area findAreaById(String Name)
    + JSONObject toJson(int depth)
}
' Abstract Component
abstract class Area {
    + String getName()
    + ArrayList<Door> getDoorsGivingAccess()
    + Area findAreaById(String Name)
    + JSONObject toJson(int depth)
}

class DirectoryAreas {
    - static DirectoryAreas instance
    - static ArrayList<Area> allAreas
    - static Partition building
    - static Area rootArea
    + static DirectoryAreas getInstance()
    + static void makeAreas()
    + static Area findAreaById(String name)
}
' Leaf
class Space extends Area {
    - ArrayList<Door> doorList
    - String name
    + Space(String s)
    + String getName()
    + void addDoor(String id)
    + ArrayList<Door> getDoorsGivingAccess()
    + Area findAreaById(String Name)
    + JSONObject toJson(int depth)
}

' Composite
class Partition extends Area {
    - ArrayList<Area> spaceList
    - String name
    + Partition(String s)
    + void add(Area area)
    + ArrayList<Area> getAreas()
    + String getName()
    + ArrayList<Door> getDoorsGivingAccess()
    + Area findAreaById(String Name)
    + JSONObject toJson(int depth)
}

class User {
- name : String
- credential : String
+ User(name: String, credential: String)
+ toString() : String
}

Door --> Space : "fromSpace"
Door --> Space : "toSpace"
DirectoryAreas -->"*" Area
Door --> State : current state >
State <|-- Locked
State <|-- Unlocked


class Main {
+ {static} main(args : String)
}

note right of Main::main
DirectoryDoors.makeDoors()
DiretoryUsers.makeUsers()
new Webserver()
end note

Main -[hidden]down- Webserver
Webserver -[hidden]down- DirectoryDoors
DirectoryDoors -[hidden]right- DirectoryUsers
@enduml
